-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Engine", function (namespace)
  namespace.class("GameObject", function (namespace)
    local yes
    yes = function (this)
      System.Console.WriteLine("yes")
      --meow();
    end
    return {
      name = "LUA NAME",
      yes = yes
    }
  end)
end)
