-- Generated by CSharp.lua Compiler
return function (path)
  return System.init({
    path = path,
    files = {
      "EngineAPI",
      "GameObject",
      "test"
    },
    types = {
      "Engine.EngineAPI",
      "Engine.GameObject",
      "Program"
    },
    Main = "Program.Main"
  })
end
