-- Generated by CSharp.lua Compiler
local System = System
local Engine
System.import(function (out)
  Engine = out.Engine
end)
System.namespace("", function (namespace)
  namespace.class("Program", function (namespace)
    local Main, AddComponent
    Main = function ()
      System.Console.WriteLine("hello lua!")
      AddComponent()
    end
    AddComponent = function ()
      System.Console.WriteLine("Adding Component")
      System.Console.WriteLine("HEHE KEBAB")

      local gameObject = Engine.GameObject()
      System.Console.WriteLine(gameObject.name)


      -- EngineAPI.AddGameObject();
      -- Console.WriteLine(Library.getInt());
    end
    return {
      Main = Main,
      AddComponent = AddComponent,
      hehe = 10
    }
  end)
end)
