-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Scripting", function(namespace)
  namespace.class("EngineAPI", function(namespace)
    local AddGameObject, Log
    AddGameObject = function()
      System.Console.WriteLine("AddGameObject()")
      _addGameObject()
    end
    Log = function()
      System.Console.WriteLine("Log()")
      AddGameObject()
    end
    return {
      AddGameObject = AddGameObject,
      Log = Log
    }
  end)
end)
