-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Potatis", function (namespace)
  namespace.class("Library", function (namespace)
    local yes
    yes = function ()
      System.Console.WriteLine("yes")
      --meow();
    end
    return {
      kebabrulle = 132420,
      yes = yes
    }
  end)
end)
