-- Generated by CSharp.lua Compiler
return function (path)
  return System.init({
    path = path,
    files = {
      "Library",
      "test"
    },
    types = {
      "Potatis.Library",
      "Program"
    },
    Main = "Program.Main"
  })
end
