-- Generated by CSharp.lua Compiler
return function (path)
  return System.init({
    path = path,
    files = {
      "EngineAPI",
      "Library",
      "test"
    },
    types = {
      "Potatis.Library",
      "Program",
      "Scripting.EngineAPI"
    },
    Main = "Program.Main"
  })
end
