-- Generated by CSharp.lua Compiler
local System = System
System.namespace("", function (namespace)
  namespace.class("Program", function (namespace)
    local Main, AddComponent
    Main = function ()
      System.Console.WriteLine("hello lua!")
      AddComponent()
    end
    AddComponent = function ()
      System.Console.WriteLine("Adding Component")
      System.Console.WriteLine("HEHE KEBABXDXDXXD")
    end
    return {
      Main = Main,
      AddComponent = AddComponent,
      hehe = 10
    }
  end)
end)
