Use Dark Theme: true
Show Gizmos: true
Use Serialization: true
Draw Bounding Boxes: false
Enable User Retention: false
Enable Depth Test: true
Enable Face Culling: true
Draw Wireframe: false
Use Multi Sampling: true