Use Dark Theme: true
Show Gizmos: true
Use Serialization: true
Enable Scripting: false
Default Game: Snake3D
Enable Depth Test: true
Enable Face Culling: false
Draw Wireframe: false
Use Multi Sampling: true
Draw Colliders: false
Draw Collider AABBs: false
Draw Mesh Bounding Boxes: true
Background Color: [0, 0, 1]
Enable Fog: false
Start Fog Distance: 0
End Fog Distance: 100