Use Dark Theme: true
Show Gizmos: true
Use Serialization: true
Enable User Retention: false
Enable Scripting: false
Default Game: Snake3D
Enable Depth Test: true
Enable Face Culling: true
Draw Wireframe: false
Use Multi Sampling: true
Draw Bounding Boxes: false