-- Generated by CSharp.lua Compiler
local System = System
local Engine
System.import(function (out)
  Engine = out.Engine
end)
System.namespace("Engine", function (namespace)
  namespace.class("EngineAPI", function (namespace)
    local AddGameObject, Log, GetComponentGameObject
    AddGameObject = function ()
      System.Console.WriteLine("AddGameObject()")
    end
    Log = function ()
      System.Console.WriteLine("Log()")
       _log();
    end
    GetComponentGameObject = function ()
      local gameObject = Engine.GameObject()
      return gameObject
    end
    return {
      AddGameObject = AddGameObject,
      Log = Log,
      GetComponentGameObject = GetComponentGameObject
    }
  end)
end)
