-- Generated by CSharp.lua Compiler
local System = System
local Engine
System.import(function (out)
  Engine = out.Engine
end)
System.namespace("Engine", function (namespace)
  namespace.class("GameObject", function (namespace)
    local __ctor__
    __ctor__ = function (this)
      this.transform = Engine.Transform()
    end
    return {
      isVisible = true,
      name = "GameObject",
      __ctor__ = __ctor__
    }
  end)
end)
