-- Generated by CSharp.lua Compiler
local System = System
local SystemNumerics = System.Numerics
System.namespace("Engine", function (namespace)
  namespace.class("Transform", function (namespace)
    local __ctor__
    __ctor__ = function (this)
      this.transformMatrix = SystemNumerics.Matrix4x4.getIdentity()
      this.position = SystemNumerics.Vector3.getZero()
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
