-- Generated by CSharp.lua Compiler
return function (path)
  return System.init({
    path = path,
    files = {
      "API.EngineAPI",
      "API.GameObject",
      "test"
    },
    types = {
      "Engine.EngineAPI",
      "Engine.GameObject",
      "TestComponent"
    }
  })
end
