-- Generated by CSharp.lua Compiler
local System = System
local Engine
System.import(function (out)
  Engine = out.Engine
end)
System.namespace("", function (namespace)
  namespace.class("TestComponent", function (namespace)
    local Update, Initialize, __ctor__
    __ctor__ = function (this)
      this.gameObject = Engine.GameObject()
    end
    Update = function (this)
      System.Console.WriteLine("Update TestComponent")
    end
    Initialize = function (this)
      System.Console.WriteLine("Initialize TestComponent")
      System.Console.WriteLine(this.gameObject.name)
      System.Console.WriteLine(this.Id)
      System.Console.WriteLine(this.gameObject.transform.position.X)

      Engine.EngineAPI.Log()
    end
    return {
      Update = Update,
      Initialize = Initialize,
      __ctor__ = __ctor__
    }
  end)
end)
